project:
  type: website
  output-dir: docs

website:
  title: "NBC Assessment"
  navbar:
    left:
      - href: insights.qmd
        text: Insights
      - href: analysis.qmd
        text: Analysis
      - href: exploration.qmd
        text: Exploration
      - href: insights_code.qmd
        text: Code Insights

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



