project:
  type: website

website:
  title: "nbc_project"
  navbar:
    left:
      - href: insights.qmd
        text: Insights
      - href: analysis.qmd
        text: Analysis
      - href: exploration.qmd
        text: Exploration

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



